services:

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ShareBuyDB
      - POSTGRES_USER=adminDB
      - POSTGRES_PASSWORD=adminDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ShareBuyDB -U adminDB"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  user-service:
    build:
      context: .
      dockerfile: ./services/User/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - DB_USER=adminDB
      - DB_PASS=adminDB
      - DB_NAME=ShareBuyDB
    depends_on:
      db:
        condition: service_healthy

  authentication-service:
    build:
      context: .
      dockerfile: ./services/Authentication/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=6000
      - DB_HOST=db
      - DB_USER=adminDB
      - DB_PASS=adminDB
      - DB_NAME=ShareBuyDB
    depends_on:
      db:
        condition: service_healthy

  group-service:
    build:
      context: .
      dockerfile: ./services/Group/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=7000
      - DB_HOST=db
      - DB_USER=adminDB
      - DB_PASS=adminDB
      - DB_NAME=ShareBuyDB
    depends_on:
      db:
        condition: service_healthy

  api-gateway:
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "443:443"
    environment:
      - NODE_ENV=production
      - PORT=443
    depends_on:
      - user-service
      - authentication-service
      - group-service

volumes:
  pgdata: