services:
  user-service:
    build:
      context: .
      dockerfile: ./User/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - DB_USER=your_database_user
      - DB_PASS=your_database_password
      - DB_NAME=your_database_name
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=your_database_name
      - POSTGRES_USER=your_database_user
      - POSTGRES_PASSWORD=your_database_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: