services:
  user-service:
    build:
      context: .
      dockerfile: ./User/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=db
      - DB_USER=adminDB
      - DB_PASS=adminDB
      - DB_NAME=ShareBuyDB
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ShareBuyDB
      - POSTGRES_USER=adminDB
      - POSTGRES_PASSWORD=adminDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: